### ISSUE TITLE
Star Count oddities

### ISSUE THREAD

**Issue by akuru-q** [emanuelef/daily-stars-explorer#143]
Hi, first up, that's a really cool project! I'm currently working on something where your data comes in super handy :)
 
But, I've noticed that there is some odd stuff happening.
I looked up the star history of Leaflet/Leaflet, and that repository starts out with 1670 stars on its creation date, which I don't think is possible.

And if I further look at snapshots of the Wayback Machine, the total star counts also don't line up with the data recovered by your app. 
Like here, for example, a snapshot from 12-06-2014, with 7779 stars: https://web.archive.org/web/20140612045120/http://github.com/Leaflet/Leaflet
Whereas if I look at the exported .csv of the Daily Stars Explorer, I see this data: 12-06-2014,9,6941; which means 6941 stars. 

That's a pretty large discrepancy, which seems like a bug.

**Comment by emanuelef** [comment]
Hi, thanks for looking into this project.

The data comes from GH GraphQL APIs. I tried to verify using other GH star history tools (for some you need to pass your PAT) and they are reporting the same data.

https://seladb.github.io/StarTrack-js/#/
<img width="1194" alt="Screenshot 2024-05-27 at 13 17 55" src="https://github.com/emanuelef/daily-stars-explorer/assets/48717/68e61bb5-452e-4188-b255-4c12bcbe0e25">

Or on

https://stars.yangerxiao.com
I cannot find a way to get a screenshot on the exact date.

**Comment by emanuelef** [comment]
Bootstrap starts with ~22k stars https://emanuelef.github.io/daily-stars-explorer/#/twbs/bootstrap
And you can see the same on 
<img width="819" alt="Screenshot 2024-05-27 at 13 29 13" src="https://github.com/emanuelef/daily-stars-explorer/assets/48717/64220b13-77bf-45b3-b7ab-1961e3734eb2">

**Comment by emanuelef** [comment]
On such cases (big spikes at the beginning) you can try the Normalise option, or the Log Y-Axis.

**Comment by emanuelef** [comment]
<img width="596" alt="Screenshot 2024-05-27 at 13 45 25" src="https://github.com/emanuelef/daily-stars-explorer/assets/48717/7e25b006-aaaa-43ab-aede-dcdb0789dd69">

**Comment by akuru-q** [comment]
Even https://stars.yangerxiao.com/ reports the same data for 12-06-2014 for Leaflet:
![Screenshot 2024-05-27 144934](https://github.com/emanuelef/daily-stars-explorer/assets/115506513/2feac6ee-3c43-42b2-b6d4-47bea5fb5870)

So, it seems like the problem stems from Github's GraphQL API, as all of the projects report the same thing as yours. The data reported by Github's API is definitely not consistent with snapshots from the Wayback Machine

**Comment by emanuelef** [comment]
yes, it would be interesting to know about those spikes at the beginning. I guess the only way is to ask someone in GitHub. 
I cannot comment on the Wayback Machine discrepancies, the tools using GH APIs seem to be aligned.
One reason where the number of stars go down can be because GH detected some fake accounts (you can read more here https://dagster.io/blog/fake-stars). Not sure this is the case for the repos you are analysing.
Another reasons for stars to go down if users un-star a repo, so if you refetch the entire history at a later time those stars that were there at some point will be missing.

**Comment by emanuelef** [comment]
@akuru-q Let me know if we can close the issue. 
Should you find out why those spikes are there let me know.
You can open a Discussion here: https://github.com/emanuelef/daily-stars-explorer/discussions. I'm sure other s would be interested.

**Comment by akuru-q** [comment]
Yeah, I think we can close the issue, because the problem - if there is any - is not related to your project at all.

Fake stars could definitely add up over the years and explain the discrepancy. But we're talking about ~1000 stars in the case of the Leaflet repo that are now missing between the Github API data and the Wayback Machine snapshot. That would mean that 1/7th of all the stars at that time were either "fake", people un-starred or deleted their accounts, and those stars are missing for those reasons now. That still seems like a large portion of stars.
