### ISSUE TITLE
Include website to "backend" container

### ISSUE THREAD

**Issue by mms-gianni** [emanuelef/daily-stars-explorer#194]
Hi,

I was about to create something similar when I discovered this project, which aligns closely with my plans. 

I've identified three minor improvements and submitted a PR for them. I apologize for the multiple submissions; it simplifies the merging or rejection process.

I noticed that the website isn't included in the container, and I think a brief message on the root path would be helpful. 😄

Additionally, I suggest serving a prebuilt version of the Vite app within the container as static content. I can submit a PR for that as well, but given the scope of the change, I’d prefer to discuss it first before investing too much time.

**Comment by emanuelef** [comment]
Hi @mms-gianni,
Thank you so much for your feedback and contributions!
I'm really glad to hear that you find the project interesting. As you might have noticed, this began as a personal project, and I haven’t had much time recently to work on it. Both the server-side code and especially the frontend could benefit from some refactoring and cleanup.

I really appreciate your suggestions, at some point I wanted to write some instructions so people can self-host it and provide their own GH PAT.

Feel free to share any ideas or suggestions in the [GitHub Discussions](https://github.com/emanuelef/daily-stars-explorer/discussions) section. I’d love to hear your thoughts!

**Comment by emanuelef** [comment]
> Additionally, I suggest serving a prebuilt version of the Vite app within the container as static content. I can submit a PR for that as well, but given the scope of the change, I’d prefer to discuss it first before investing too much time.

Definitely something that would be super useful.
The hosted version is using my PAT and some people would like to self-host.

**Comment by mms-gianni** [comment]
It was simpler as expected.

**Comment by emanuelef** [comment]
Fantastic! Closing this Issue following the merging of https://github.com/emanuelef/daily-stars-explorer/pull/195

**Comment by mms-gianni** [comment]
@emanuelef had a quick [dive](https://github.com/wagoodman/dive) into image details. 

The image grew by ~4MB from 36MB to 40MB 

![image](https://github.com/user-attachments/assets/093fd807-82ab-402a-8542-f7e487c9fa5a)
