### ISSUE TITLE
Date range is not refreshing to current date

### ISSUE THREAD

**Issue by yuzupartycat** [emanuelef/daily-stars-explorer#196]
<img width="1451" alt="Pasted_Image_11_22_24__3_13 PM" src="https://github.com/user-attachments/assets/8c040dcc-4410-424b-a559-aa79ebda34a4">
<img width="1458" alt="Pasted_Image_11_22_24__3_14 PM" src="https://github.com/user-attachments/assets/c1179d05-4dce-494c-9b22-032bc93b911f">

This is a cool tool, I've just started using it, but I've been encountering an issue the last few days trying to look at this repo https://emanuelef.github.io/daily-stars-explorer/#/nrwl/nx

The date range is limited to 11/17/2024. It looks like the helm/helm is refreshing through yesterday 11/21/2024 but the nrwl/nx one is stuck at the 17th. Is this a bug or am I using the tool incorrectly?

**Comment by emanuelef** [comment]
@yuzupartycat, thank you for using the tool and sharing your feedback!

Currently, when new repo stars are fetched, the history is retained for 10 days to prevent having to refetch the entire history each time. If you want to refresh the data to include the previous day, you can do so by checking the "Update" checkbox and clicking the "Fetch" button again.

I realize the explanation provided when you hover over the info icon isn't very clear. I'll work on making that more visible and easier to understand.

**Comment by yuzupartycat** [comment]
> If you want to refresh the data to include the previous day, you can do so by checking the "Update" checkbox and clicking the "Fetch" button again.
I can see in the second screenshot the Update checkbox appeared, that's when the history is not updated to the previous day.

@emanuelef thanks for letting me know, this worked for me :)
