### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shuvashish76** [emanuelef/daily-stars-explorer#72]
Hello, awesome project. What's the license of this project?

**Comment by emanuelef** [comment]
Thanks for pointing that out, I was thinking of using MIT.

**Comment by emanuelef** [comment]
@shuvashish76 Happy to have a chat about this project if you have other suggestions or you are interested in contributing.

**Comment by shuvashish76** [comment]
Added with https://github.com/emanuelef/daily-stars-explorer/commit/9cbff3f1a256437b5481e7068d4751a2dc9af185 thanks.

**Comment by shuvashish76** [comment]
Thanks for the license :D
Sorry I'm not a dev but I've a question what library is used for the graphs?
There is an awesome opensource chart library do check it out : https://www.chartjs.org/
Lichess recently [switched](https://lichess.org/feed#GaJCZJ) to this library & I got to know about this library from there.

**Comment by emanuelef** [comment]
@shuvashish76 
I found https://www.fusioncharts.com/fusiontime and it works perfectly for what I needed.
I'll have a closer look at https://www.chartjs.org/ when I was looking for a library to use the line chart they had didn't seem to have the features I needed. But it might have changed.

Thanks for any comment/suggestion and feel free to start a Discussion, I'm happy to know people are using this tool.
