### ISSUE TITLE
Show the derivative of the star history curve

### ISSUE THREAD

**Issue by Kerollmops** [emanuelef/daily-stars-explorer#93]
Would it make sense to show [the derivative of the star history curve](https://en.wikipedia.org/wiki/Derivative)? This corresponds to the acceleration of the curve (or acceleration) and would help spot the speed or slowdown of the number of stars on a repo.

Doing the difference between one point of the curve and the next one and showing this curve would probably make it too 🤔

**Comment by emanuelef** [comment]
Hi @Kerollmops, that's a good idea.
I have a PR where I'm trying to get a good trend line, I tried LOESS but I guess there must be something better.
I think for the acceleration I should use second derivative, curious to see how it looks like and if it's giving some indication.

**Comment by emanuelef** [comment]
@Kerollmops I've been working on adding some new data manipulation options, which I'm tentatively calling "transformations" for now. These include calculations for the first and second-order derivative.
To further enhance trend identification, I'm also exploring alternatives to LOESS. Splines might be a promising approach.

Running average now has a hardcoded 120 days size window, which might not be suitable for repos that have been created recently. 

Any suggestion is welcome!

**Comment by Kerollmops** [comment]
I tried the feature on the meilisearch repository and found it hard to understand what all those curves mean and how they can be interpreted. What could be fantastic is a small description of how to read the blue curve.

Also, a good explanation of how the running median/average work could be interesting because, as I understand it, it becomes unusable on the far right points of the graph. Because it will only average/median the 60 points on the left of it.

- LOESS: What is it? How does it work?
- Running Average: Does it mean that the mounts correspond to periods when you get a lot of stars?
- Running Median: Is it the same as the average?
- Derivative: Is it the speed or the acceleration? It seems to be the latter, but how can we see the speed?
- Second Derivative: What does it correspond to? Is it the acceleration of the acceleration?

Thank you very much for the great soft!

**Comment by emanuelef** [comment]
Added the ability to select different ways to aggregate or calculate the original data, this include the derivative: https://github.com/emanuelef/daily-stars-explorer/blob/main/aggregate.md#derivative

I created a discussion https://github.com/emanuelef/daily-stars-explorer/discussions/102 so it's possible to make other suggestions.
